### ISSUE TITLE
error installing on Windows 10

### ISSUE THREAD

**Issue by tommck** [yuanyan/node-optimage#4]
```
npm WARN deprecated find-file@0.1.4: Use the globby package instead
C:\Users\tom\AppData\Roaming\npm\optimage -> C:\Users\tom\AppData\Roaming\npm\node_modules\optimage\bin\optimage

> gifsicle@0.1.7 postinstall C:\Users\tom\AppData\Roaming\npm\node_modules\optimage\node_modules\gifsicle
> node index.js

path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/imagemin/gifsicle-bin/v0.1.7/vendor/win/x86/gifsicle.exe',
  name: 'gifsicle.exe',
  os: 'win32',
  arch: 'x64' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:799:5)
    at C:\Users\tom\AppData\Roaming\npm\node_modules\optimage\node_modules\download\index.js:35:43
    at each (C:\Users\tom\AppData\Roaming\npm\node_modules\optimage\node_modules\each-async\each-async.js:63:4)
    at module.exports (C:\Users\tom\AppData\Roaming\npm\node_modules\optimage\node_modules\download\index.js:33:5)
    at C:\Users\tom\AppData\Roaming\npm\node_modules\optimage\node_modules\bin-wrapper\index.js:108:20
    at C:\Users\tom\AppData\Roaming\npm\node_modules\optimage\node_modules\bin-wrapper\index.js:141:24
    at C:\Users\tom\AppData\Roaming\npm\node_modules\optimage\node_modules\bin-check\index.js:30:20
    at C:\Users\tom\AppData\Roaming\npm\node_modules\optimage\node_modules\executable\index.js:39:20
    at FSReqWrap.oncomplete (fs.js:123:15)
C:\Users\tom\AppData\Roaming\npm
```

**Comment by pedrofracassi** [comment]
I'm getting the same thing

**Comment by Rambatino** [comment]
Everyone gets that I believe.

**Comment by GhimireS** [comment]
Yes please . i get the same error .. whats the update?
